### ISSUE TITLE
Form load with Ajax checkboxes are not replaced

### ISSUE THREAD

**Issue by simonsolutions** [shaheenhyderk/slideon#2]
When I load a form content with ajax request, the checkboxes is not replaced. the javascript for the "slideon-auto" class is not called. 
Is there a way to call it manually or what would be the best practice for checkboxes that are not there when document loads?

**Comment by shaheenhyderk** [comment]
First of all thanks for your feedback. I have added a new release 1.0.2 which includes your requirement. 

Now you have to add a script tag, create an object of slideon and call the load function. so now you can call the load function whenever you are adding dynamic checkboxes. I have added the usage in https://shaheenhyder.com/slideon

Hope it solves your issue, expecting more feedback, suggestions, and issues.
